# `r fontawesome::fa("calendar-alt")` Schedule. {#sec-schedule}

`r fontawesome::fa("credit-card")` ARF2, Spring 2024. Room  4403 A, 16:00 – 17:30. Zoom [https://us02web.zoom.us/j/85044414325](https://us02web.zoom.us/j/85044414325)

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Thursday, 11 January.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts. You should have received invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members. You should have received an invitation in your UDEM student email.

**Session 2. Monday, 15 January.**

- Reading. @drake2010basics, Chapter 9 *Financial risk management*. 
- Complementary material. @crouhy2014essentials, video 1 [The building blocks of risk management.](https://youtu.be/sKMt1qzmGfU); video 2 [Risk management: A helicopter view.](https://youtu.be/PJbRtIVGdaI); video 3 [Corporate risk management: A primer.](https://youtu.be/YWpfwi8wD4c).
- Complementary material. @brealey2020principles, Chapter 26 *Managing risk*. @crouhy2014essentials, Chapter 1 *Risk management a helicopter view*. @crouhy2014essentials, Chapter 2 *Corporate risk management a primer*.

**Session 3. Thursday, 18 January.**

- Reading. @drake2010basics, Chapter 9 *Financial risk management*. 
- Complementary material. @crouhy2014essentials, video 1 [The building blocks of risk management.](https://youtu.be/sKMt1qzmGfU); video 2 [Risk management: A helicopter view.](https://youtu.be/PJbRtIVGdaI); video 3 [Corporate risk management: A primer.](https://youtu.be/YWpfwi8wD4c).
- Complementary material. @brealey2020principles, Chapter 26 *Managing risk*. @crouhy2014essentials, Chapter 1 *Risk management a helicopter view*. @crouhy2014essentials, Chapter 2 *Corporate risk management a primer*.
- Extra marks 1/8. DataCamp course: *Credit risk modeling in R*, before 10:00 a.m.

**Session 4. Monday, 22 January.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.

**Session 5. Thursday, 25 January.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- To know more about regression with a binary dependent variable, and references to credit risk please see @hanck2020introduction, Chapter 11. @hull2020machine, Chapter 3.
- Actividad +5 puntos sobe la calificación del primer parcial. Compartir, reaccionar y/o agregar un comentario en redes sociales. *Retos y oportunidadades en el aprendizaje de ciencia de datos en las escuelas de negocios.* [Episodio en Spotify](https://open.spotify.com/episode/6x8c6XIPIfIPLj1yRhi5D8?si=5s9ik8ffQcW_Sy9NVU5sxg); [episodio en YouTube](https://youtu.be/SKG3Kr-TK-w?si=W5wg2DXluuiEspWC). Café de Datos, Datlas. Temporada 9, capítulo 132. Subir eviencia (screenshot) al foro de discusión del primer parcial. La hora límite es 10:00 am de la sesión 5.

**Session 6. Monday, 29 January.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- Reading. Mensajes del futuro para ARF.
- Complementary material. @alonso2021understanding.
- Extra marks 2/8. DataCamp skill track: *R programming*, before 10:00 a.m.

**Session 7, Zoom. Thursday, 1 February.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- Extra marks. Mentimeter 1/4.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 5 February.**

**Session 8. Thursday, 8 February.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- Complementary material. Video: [Ethics and trust in the investment profession.](https://youtu.be/azBhDSjBRS0)
- Extra marks 3/8. [Introduction to Sustainable Finance (NEW).](https://unccelearn.org/course/view.php?id=139&page=overview) Submit your PDF certificate before 10:00 a.m. by the discussion forum.

**Session 9. Monday, 12 February.**

- Reading. @Hull9, Section 24.1 Credit ratings; Section 24.2 Historical default probabilities; Section 24.3 Recovery rates.
- Complementary material. Fictional video (warning, it has offensive language): [FrontPoint partners confronts Morgan Stanley risk assessors and S&P.](https://youtu.be/Vvxbc8L4s64)
- Complementary material. PowerPoint slides: [John C. Hull.](https://www-2.rotman.utoronto.ca/~hull/ofodslides/index.html)
- Activity. $H_1$ review.

**Session 10, Zoom. `r fontawesome::fa("heart", fill = "red")` Thursday, 15 February.**

- Graded. Complete $H_1$ before 10:00 a.m.

**Session 11. Monday, 19 February.**

- Activity. $E_1$ review.

**Session 12, Zoom. Thursday, 22 February.**

- Graded. $E_1$ Instructions in Blackboard.

## `r fontawesome::fa("battery-half")` Part 2.

**Session 13. Monday, 26 February.**

- Activity. Discuss $E_1$ answers.
- Graded. Submit $H_1$ and $E_1$ auto and co-evaluation before 10:00 a.m. Instructions in Blackboard.
- Extra marks. The wheel of fortune 1/3.

**Session 14. Thursday, 29 February.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Extra marks 4/8. DataCamp course: *Introduction to ChatGPT*, before 10:00 a.m.

**Session 15, Zoom. Monday, 4 March.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Complementary material. @brealey2020principles, Chapter 23 *Credit risk and the value of corporate debt*.

**Session 16. `r fontawesome::fa("female")` Thursday, 7 March.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Complementary material. Video: [FRM: How $d_2$ in Black-Scholes becomes PD in Merton model.](https://youtu.be/lV0ytJYbVzc)

**Session 17. Monday, 11 March.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Complementary material. Video: [Measuring credit risk.](https://youtu.be/03nNzt8PyYM)
- Extra marks 5/8. DataCamp skill track: *Data Visualization with R*, before 10:00 a.m.

**Session 18, Zoom. $\pi$ Thursday, 14 March.**

- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Extra marks. Mentimeter 2/4.
- Activity. $H_2$ review.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 18 March.**

**Session 19. Thursday, 21 March.**

- Graded. Complete $H_2$ before 10:00 a.m.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 25 March.**

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, 28 March.**

**Session 20, Zoom. Monday, 1 April.**

- Extra marks. Mentimeter 3/4.
- Activity. $E_2$ review.

**Session 21, Zoom. Thursday, 4 April.**

- Graded. $E_2$ Instructions in Blackboard.

## `r fontawesome::fa("battery-three-quarters")` Part 3.

**Session 22. Monday, 8 April.**

- Activity. Discuss $E_2$ answers.
- Graded. Submit $H_2$ and $E_2$ auto and co-evaluation before 10:00 a.m. Instructions in Blackboard.
- Extra marks. The wheel of fortune 2/3.

**Session 23. Thursday, 11 April.**

- Reading. @drake2010basics, Chapter 15 *Investment management*.
- Extra marks 6/8. [Introduction to Green Economy.](https://unccelearn.org/course/view.php?id=51&page=overview) Submit your PDF certificate before 10:00 a.m. by the discussion forum.
- Complementary material. [The Plastic Recycling Myth.](https://youtu.be/zZlRhCDzh2A)

**Session 24. Monday, 15 April.**

- Reading. @Hull9, Chapter 22 *Value at Risk (sections 22.1 to 22.4)*.
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.

**Session 25. Thursday, 18 April.**

- Reading. @Hull9, Chapter 22 *Value at Risk (sections 22.1 to 22.4)*.
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.

**Session 26. Monday, 22 April.**

- Reading. @Hull9, Chapter 22 *Value at Risk (sections 22.1 to 22.4)*.
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.
- Extra marks 7/8. DataCamp skill track: *Python Programming*, before 10:00 a.m.

**Session 27, Zoom. Thursday, 25 April.**

- Reading. @drake2010basics, Chapter 16 *The theory of portfolio selection*.
- Complementary material. @brealey2020principles, Chapter 8 *Portfolio theory and the capital asset pricing model*.
- To know more about portfolio selection see @ruppert2011statistics, Chapters 16.
- Extra marks. Mentimeter 4/4.
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)

**Session 28, Zoom. `r fontawesome::fa("children")` Monday, 29 April.**

- Reading. @Hull9, Section 23.8 *Estimating volatilities and correlations*. 
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.

**Session 29. `r fontawesome::fa("jedi-order")` Thursday, 2 May.**

- Reading. @Hull9, Section 23.8 *Estimating volatilities and correlations*. 
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.
- Extra marks 8/8. DataCamp skill track: *Data Visualization with Python*, before 10:00 a.m.

**Session 30. Monday, 6 May.**

- Reading. @Hull9, Section 23.8 *Estimating volatilities and correlations*. 
- Reading. @lozanoIF, Chapter 5 *Value at Risk*.
- Non-graded. Complete $H_3$ before 10:00 a.m.

**Session 31, Zoom. `r fontawesome::fa("female")` Thursday, 9 May.**

- Activity. $E_F$ review.
- Extra marks. The wheel of fortune 3/3.
- Farewell.

## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Thursday, 23 May, 16:00 – 18:00.**

- Graded. $E_F$ Instructions in Blackboard.
