---
title: ''
  html_document:
    df_print: paged
---

\newpage

# `r fontawesome::fa("calendar-alt")` Class schedule. 

ARF1, Spring 2023. Room 2102, 16:00 – 17:30.

## Part 1. `r fontawesome::fa("battery-quarter")`

**Session 1. `r fontawesome::fa("handshake")` Thursday, 12 January.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts, you should have invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members, you should have an invitation in your UDEM student email.

**Session 2. Monday, 16 January.**

- Reading. @crouhy2014essentials, Chapter 1 *Risk management a helicopter view*.
- Complementary material. @crouhy2014essentials, video 1 [The building blocks of risk management.](https://youtu.be/sKMt1qzmGfU) video 2 [Risk management: A helicopter view.](https://youtu.be/PJbRtIVGdaI)
- Complementary material. @brealey2020principles, Chapter 26 *Managing risk*.
- Non graded. Register and attend the following DataCamp webinar. [Exploratory data analysis in R for absolute beginners.](https://www.datacamp.com/webinars/data-analysis-r-beginners)

**Session 3. Thursday, 19 January.**

- Reading. @crouhy2014essentials, Chapter 2 *Corporate risk management a primer*.
- Complementary material. @crouhy2014essentials, video [Corporate risk management: A primer.](https://youtu.be/YWpfwi8wD4c)

**Session 4. Monday, 23 January.**

- Extra marks. DataCamp course: *Credit risk modeling in R* by Lore Dirick. before 7:00 a.m.
- Reading. @crouhy2014essentials, Chapter 2 *Corporate risk management a primer*.
- Reading. @lozanoARF, Chapter 1 *Loan analysis*.

**Session 5. Thursday, 26 January.**

- Extra marks. DataCamp skill track: *R programming*. before 7:00 a.m.
- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- To know more about regression with a binary dependent variable, and references to credit risk please see @hanck2020introduction, Chapter 11. @hull2020machine, Chapter 3.

**Session 6. Monday, 30 January.**

- Reading. @lozanoARF, Chapter 1 *Loan analysis*.
- Reading. Mensajes del futuro para ARF.
- Complementary material. @alonso2021understanding.


**Session 7, Zoom. Thursday, 2 February.**

- Extra marks. $ME_1$ Instructions in Blackboard.
- Super extra marks. DataCamp assessment: *R programming*.
- Reading. @lozanoARF, Chapter 1 *Loan analysis*.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 6 February.**

**Session 8. Thursday, 9 February.**

- Activity. $H_1$ review.
- Reading. @Hull9, Section 24.1 Credit ratings; Section 24.2 Historical default probabilities; Section 24.3 Recovery rates.
- Complementary material. Fictional video (warning, it has offensive language): [FrontPoint partners confronts Morgan Stanley risk assessors and S&P.](https://youtu.be/Vvxbc8L4s64)
- Complementary material. Video: [Ethics and trust in the investment profession.](https://youtu.be/azBhDSjBRS0)
- Complementary material. PowerPoint slides: [John C. Hull.](https://www-2.rotman.utoronto.ca/~hull/ofodslides/index.html)

**Session 9. `r fontawesome::fa("heart")` Monday, 13 February.**

- Graded. Complete $H_1$ before 7:00 a.m.
- Activity. Review $H_1$ answers.
- Activity. $E_1$ review.

**Session 10, Zoom. Thursday, 16 February.**

- Graded. $E_1$ Instructions in Blackboard.


## Part 2. `r fontawesome::fa("battery-half")`

**Session 11, Zoom. Monday, 20 February.**

- Activity. Review $E_1$ answers.
- Extra marks. The wheel of fortune 1/3.
- Graded. Submit $H_1$ and $E_1$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.
- Extra marks. DataCamp skill track: *Data visualization with R*. before 7:00 a.m.
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)


**Session 12. Thursday, 23 February.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Complementary material. @brealey2020principles, Chapter 23 *Credit risk and the value of corporate debt*.


**Session 13. Monday, 27 February.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.
- Complementary material. Video: [FRM: How $d_2$ in Black-Scholes becomes PD in Merton model.](https://youtu.be/lV0ytJYbVzc)
- Extra marks. DataCamp skill track: *Finance fundamentals in R*. before 7:00 a.m.


**Session 14. Thursday, 2 March.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.


**Session 15. `r fontawesome::fa("female")` Monday, 6 March.**

- Extra marks. [Open online course on gender and environment.](https://unccelearn.org/course/view.php?id=39&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.
- Class activity. Analysis of the Mexican economy.
- Readings. Look for a recent and relevant Banxico presentation: [Banxico.](https://www.banxico.org.mx/publicaciones-y-prensa/presentaciones/presentaciones-junta-gobierno.html)


**Session 16. Thursday, 9 March.**

- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.


**Session 17. $\pi$ Monday, 13 March.**

- Activity. $H_2$ review.
- Reading. @Hull9, Section 24.6 *Using equity prices to estimate default probabilities*.
- Reading. @lozanoARF, Chapter 2 *The Merton model*.

**Session 18, Zoom. Thursday, 16 March.**

- Extra marks. $ME_2$ Instructions in Blackboard.
- Graded. Complete $H_2$ before 7:00 a.m.
- Activity. Review $H_2$ answers.
- Activity. $E_2$ review.
- Super extra marks. DataCamp assessment: *Data visualization with R*.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 20 March.**


**Session 19, Zoom. Thursday, 23 March.**

- Graded. $E_2$ Instructions in Blackboard.

## Part 3. `r fontawesome::fa("battery-three-quarters")`

**Session 20, Zoom. Monday, 27 March.**

- Activity. Review $E_2$ answers.
- Extra marks. The wheel of fortune 2/3.
- Graded. Submit $H_2$ and $E_2$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.


**Session 21. Thursday, 30 March.**

- Reading. @Hull9, Section 24.8 *Default correlation*.
- Reading. @lozanoARF, Chapter 3 *The Gaussian copula model*.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 3 April.**

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, 6 April.**

**Session 22. Monday, 10 April.**

- Reading. @Hull9, Section 24.8 *Default correlation*.
- Reading. @lozanoARF, Chapter 3 *The Gaussian copula model*.
- Complementary material. Video: [Measuring credit risk.](https://youtu.be/03nNzt8PyYM)
- To know more about copulas see @ruppert2011statistics, Chapter 8.


**Session 23. Thursday, 13 April.**

- Reading. @Hull9, Section 24.8 *Default correlation*.
- Reading. @lozanoARF, Chapter 3 *The Gaussian copula model*.
- Extra marks. [Introduction to Green Economy.](https://unccelearn.org/course/view.php?id=51&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.


**Session 24. Monday, 17 April.**

- Reading. @Hull9, Section 24.8 *Default correlation*.
- Reading. @lozanoARF, Chapter 3 *The Gaussian copula model*.

**Session 25. Thursday, 20 April.**

- Reading. @Hull9, Section 25.1 *Credit default swaps*.
- Complementary material. Video: [Credit risk transfer mechanisms.](https://youtu.be/nEp2RfweCjs)

**Session 26. Monday, 24 April.**

- Extra marks. DataCamp skill track: *Tidyverse fundamentals with R*. before 7:00 a.m.
- Reading. @Hull9, Section 25.1 *Credit default swaps*.
- Complementary material. Fictional video: [Dr. Michael Burry betting against the housing market.](https://youtu.be/dqDu1sHoIAw)

**Session 27, Zoom. `r fontawesome::fa("children")` Thursday, 27 April.**

- Reading. @Hull9, Section 25.1 *Credit default swaps*.
- Extra marks. $ME_F$ Instructions in Blackboard.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, 1 May.**

**Session 28. `r fontawesome::fa("jedi-order")` Thursday, 4 May.**

- Reading. @Hull9, Section 25.2 *Valuation of credit default swaps*.

**Session 29. `r fontawesome::fa("female")` Monday, 8 May.**

- Reading. @Hull9, Section 25.2 *Valuation of credit default swaps*.

**Session 30, Zoom. Thursday, 11 May.**

- Non graded. Complete $H_3$ before 7:00 a.m.
- Activity. $E_F$ review.
- Extra marks. The wheel of fortune 3/3.
- Farewell.

**Session 31, Zoom. Friday, 12 May, 16:00 – 19:00.**

- Activity. Open rehearsal PEF students.

## The end. `r fontawesome::fa("battery-full")`

**Final exam, Zoom. Thursday, 25 May, 16:00 – 18:00.**

- Graded. $E_F$ Instructions in Blackboard.


\newpage





