# Learning activities. {#sec-activities}

Learning activities are structured tasks or exercises designed to facilitate the acquisition of knowledge, skills, and understanding in an educational context. They are intended to promote active engagement, deepen understanding, and support the achievement of specific learning objectives.

The learning activities are classified into graded, non-graded, and bonus points categories. 

- Graded activities are two assignments $H_1$, $H_2$, two exams $E_1$, $E_2$ and one final exam $E_F$, which account for 100% of your final grade and all of them are group activities. 
- Bonus points are awarded as a bonus to your next exam or final exam, so completing bonus points activities increases the maximum mark possible. These are optional and individual activities.
- Non-graded activities are relevant for your learning but are not included in the grading process. Therefore, failure to complete them will not result in any mark deduction. These are optional and individual activities.

The official rules for language, group work, submissions, deadlines, required questions, and attendance during review sessions are collected in [Activities policies](<course-policies.rmd#sec-ap>).

<!-- **Mock exams.** We may have one or more mock exams. These exams are similar to the regular exams as they can be taken without physical presence in the classroom. Mock exams provide an opportunity to become familiar with the examination process, logistics, and the level of difficulty of the graded exams. Mock exams are conducted as group activities, typically consisting of one or two questions. If your group answers the mock exam correctly (100% accuracy), you will receive 2 stickers (+10 marks) to be added to your next partial or final exam. However, if your group does not answer the mock exam correctly, you will lose 5 marks on your next partial or final exam. We will review the correct answers immediately during the same session. -->

## `r fontawesome::fa("check")` Exams & Homework assignments.

All topics covered in this course will be evaluated in the exams. To achieve a strong final grade, I recommend taking detailed notes throughout the semester. Homework assignments are also excellent preparation for the exams, so start working on them early. You are always welcome to share your progress with me, I’m happy to provide feedback.

**When?** The exams follow the schedule in the course calendar (@sec-schedule), aligned with the university’s official dates. In 3-hour class sessions, $E_1$ and $E_2$ take place during the first part, followed by a review of the answers in the second. Homework $H_1$, $H_2$, and $H_3$ are due shortly before $E_1$, $E_2$, and $E_F$, respectively (see course calendar). Planning ahead is strongly advised: low assignment grades are often caused by starting too late, not by difficulty.

**What are typical questions?** While past exams may be available (since I allow students to keep their copies), the course content evolves and questions change each semester. Still, reviewing older exams can help you understand the general format and types of questions. Exams often include tasks that require using R and/or Python, typically focused on analyzing and interpreting data or results. I normally take material from the course calendar @sec-schedule (readings and complementary material) as main references to write exams questions. Homework assignments include applied, research-oriented questions that require writing code in R and/or Python, learning new concepts, and conducting some independent research. You are not alone in this process: you have access to the resources outlined in the syllabus, including support through Zoom sessions, DataLab discussions, meetings, and email.

**What are the mechanics?** Exam instructions will be provided as a <tt>`.ipynb`</tt> Jupyter Notebook file, made available on Blackboard five minutes before the start of the class session (see course calendar). Once available, you must download the file and upload it to your group’s DataLab workbook, where you and your teammates will collaborate online to complete the exam within the given time frame. Save the completed notebook in your group workspace inside the “submissions” folder (see [DataCamp policies](<course-policies.rmd#sec-dcp>)). Finish before the deadline (see [Activities policies](<course-policies.rmd#sec-ap>)). I have access to your DataLab and will make an electronic copy for grading. A few days later, you’ll receive your group’s grade along with comments.

The process for homework assignments is similar: once the instructions are posted on Blackboard, upload them to your group’s DataLab workbook, complete the task online, and ensure everything is finalized in the required location before the deadline (see [Activities policies](<course-policies.rmd#sec-ap>)).

**Are we going to review the exam and homework assignment answers?** Yes. After each exam, we will use the following class session (held via Zoom) to go over the questions and discuss correct approaches. This applies to $E_1$ and $E_2$, but not to $E_F$ since classes end before the final exam results can be reviewed. Exam questions are open-ended, and there are often multiple correct ways to answer them, so we will explore a variety of valid responses and common mistakes. If more time is needed for review, we can continue the discussion on the forum, in DataLab, or through a meeting upon request. Reviewing your mistakes is an important way to learn and prepare for the final exam. For homework assignments, students receive immediate feedback during their presentations, and additional comments are available upon request.

**What if we fail to understand our own mistakes?** Regardless of the activity, if you have any difficulty understanding your mistakes, it is expected that you reach out to me for clarification. In such cases, I may request you to attempt the questions again before we can discuss your specific mistakes in a meeting. 

**Do all group members receive the same mark?** Not necessarily. Individual marks are adjusted based on coevaluation results (see [Group policies](<course-policies.rmd#sec-gp>)). For example, even if a group receives a perfect score on the first homework $G_{H1} = 100$, a student with a coevaluation score of $C_{H1} = 0$ would receive an individual mark of $H_1 = 0$. Conversely, if the group mark is $G_{H1} = 90$ and a student receives a coevaluation of $C_{H1} = 100$, their individual mark adjusts to $H_1 = 93$. In short, your final mark reflects both the group’s performance and your contribution. Additionally, exam marks may increase through participation in bonus points activities.

**Where?** Physical presence in the classroom is not required for taking the exams. You can complete the exams from any location of your choice, as they are conducted, answered, and submitted entirely in electronic format. Just ensure that you and the rest of your group have a stable internet connection. I can create Zoom rooms for your group to answer the exam if you wish. I will be available during the exams through Zoom; joining the Zoom session is not mandatory during exams, but I will be accessible in case you need assistance. The Zoom link for the exams is the same as the one assigned to the course.

For 3-hour class sessions, the first part of the session is dedicated to taking the exam. During the second part of the class, you will need to log in to the Zoom session to review and discuss the answers for the $E_1$ and $E_2$ exams. (See [Activities policies](<course-policies.rmd#sec-ap>) for attendance rules.)

**How many questions?** The number of questions and the required number of answers are defined in [Activities policies](<course-policies.rmd#sec-ap>). Read those rules carefully and answer only the required number of questions.

**Can we open the textbook during the exam?** Yes, you are allowed to use the internet and all course materials during the exams. The purpose of the exams is to assess your reasoning, coding, and analytical skills rather than your ability to memorize concepts or perform internet searches. Exam questions are designed so that answers cannot be found directly online, in the textbook, or in a test bank. Even AI tools frequently fail to provide fully correct answers because most of the time questions are very specific and data-oriented. Remember: exams are completed only with your assigned group (see [Activities policies](<course-policies.rmd#sec-ap>)).


## `r fontawesome::fa("grin-hearts")` Bonus points.

Bonus points activities are individual tasks. As with any bonus points activity, you will not lose points if you fail to complete them, but you can earn additional marks if you complete them on time. For each DataCamp course completed on time, you will receive a nice PDF certificate, which looks great on your CV and LinkedIn profile.

<!-- [^6]: Please note that DataCamp is not the only alternative to learn R. There are other free alternatives available in the web such as [Swirl.](https://swirlstats.com/) You can find many free electronic resources to learn R in the reference section at the end of this syllabus. There are also some students who find the tutorials (developed by myself) a good enough resource to learn R. However, there are other students who need more specialized courses, or more basic courses to understand the logic of programming in R and some other extensions. In my attempt to offer you as many free and useful resources as possible, you have a DataCamp account. According to Martijn Theuwissen Co-founder and COO at DataCamp, they are no.1 ranked Forbes certifications. -->

**DataCamp.** You can earn bonus points for your next $G_{E1}, G_{E1}$ and $G_{E1}$ exams group marks by completing DataCamp assignments, which involve completing skill tracks, career tracks or professional certifications. For more details, refer to the DataCamp Assignments section and the course calendar: @sec-schedule, where they are marked with the *bonus points* tag. The deadline is 10:00 on the date indicated in the course calendar.

If you complete all of them on time, you will earn:

* $X_{E1} = 15$ bonus points over your $G_{E1}$.
* $X_{E2} = 15$ bonus points over your $G_{E2}$.
* $X_{EF} = 15$ bonus points over your $G_{EF}$.

<!-- The amount of bonus points is based on the cumulative number of DataCamp assignments completed during the semester. There are 9 DataCamp assignments in total, allocated as 3 in the first part of the course, 3 in the second, and 3 in the third. Each assignment consists of accumulating 10,000 XP in DataCamp courses. For each assignment completed, you earn $f(n) = p_n$ bonus points on the total number of assignments completed, where $p_n$ represents the $n$-th prime number and $n$ is the count of completed assignments. The function domain is $\{1, 2, 3, 4, 5, 6, 7, 8, 9\}$ and the range is $\{2, 3, 5, 7, 11, 13, 17, 19, 23\}$. -->

<!-- Then, if you complete all of them on time, you will earn: -->

<!-- * $X_{E1}=f(3) = 5$ bonus points over your $G_{E1}$, which represents +2 over your final grade $F$. -->
<!-- * $X_{E2}=f(6) = 13$ bonus points over your $G_{E2}$, which represents +5.2 over your final grade $F$. -->
<!-- * $X_{EF}=f(9) = 23$ bonus points over your $G_{EF}$, which represents +6.9 over your final grade $F$. -->

<!-- Thus, if you complete all 9 bonus points DataCamp assignments on time (90,000 XP) you will get +14.1 over your final grade $F$. -->

<!-- ```{r eval=FALSE, include=FALSE} -->
<!-- cumulative <- cumsum(2:8) -->
<!-- single <- seq(2, 8) -->
<!-- x <- seq(1, 7) -->

<!-- df <- data.frame("Activity completed" = x,  -->
<!--                  "bonus points per activity" = single,  -->
<!--                  "Cumulative" = cumulative) -->
<!-- df -->
<!-- ``` -->

<!-- To complete the XP assignments, you will need to choose courses, skill tracks, career tracks, practice exercises, and other types of DataCamp content on your own. You are free to select based on your personal interests and preferences. However, if you would like some guidance, I recommend starting with basic or fundamental R programming courses, data visualization in R, as well as finance courses with R. Other options include Python, SQL, Tableau, Power BI, Excel, ChatGPT, and more. Visit the "Learn" section on DataCamp to browse, search, and filter all available learning content to accumulate XP. Feel free to contact me if you would like further advice on which courses to take. -->

<!-- **DataCamp assessments.** DataCamp assessments are individual activities that allow you to get extra marks over your final grade $F$. Yes, over your final grade. These are time-limit online evaluations of your knowledge of R and Python. DataCamp marks your assessment as N (novice), I (intermediate), and A (advanced) depending on your own performance. The rule to allocate the extra marks over your final grade $F$ is the following: 0 for N; +1 for I; and +2 for A. Assessments will be available in your DataCamp Assignments section and in the course calendar as *super extra marks* tag. Assessments are completed during the class session and although DataCamp allows you to complete the assessment twice, I will take your first try as your grade. -->

<!-- **DataCamp top 5 XP for the first 30, 60, and 90 days.** DataCamp has a leaderboard that ranks participants based on the amount of XP they earn. I will assign +5 bonus points to the top 5 students with the highest XP during three specific time ranges: the first 30 days, days 31 to 60, and days 61 to 90 of the semester. The allocation of these bonus points will be recorded according to the course calendar. -->

```{r eval=FALSE, include=FALSE}
# Fecha inicial
fecha_inicial <- as.Date("2025-08-04")

fecha_30 <- fecha_inicial + 30
fecha_60 <- fecha_30 + 30
fecha_90 <- fecha_60 + 30
  
# Sumar 30, 60 y 90 días
fechas <- data.frame(
  fecha = c(fecha_30, fecha_60, fecha_90),
  dia_semana = weekdays(c(fecha_30, fecha_60, fecha_90))
)

fechas

```

<!-- The dates on which I will assign these marks according to the DataCamp leaderboard are: Wednesday, September 3; Friday, October 3; and Monday, November 3. -->

<!-- **UN CC:Learn courses.** You can earn bonus points for your next $G_{E1}, G_{E2}$ and $G_{EF}$ exams group marks by completing [UN CC:Learn](https://www.uncclearn.org/) courses, which are listed in the course calendar under the *bonus points* tag. The deadline is 10:00 on the date indicated in the course calendar. Please note that UN CC:Learn courses may require a minimum score to obtain a valid certificate. -->

<!-- Some students may have completed a UN CC:Learn course in the past. If your certificate is older than the starting date of the current academic term, it is not valid, and you will need to choose a different course to substitute it.  -->

<!-- There are 3 UN CC:Learn activities in the semester, allocated as 1 in the first term, 1 in the second, and 1 in the third. You will earn +5 bonus points for each completed course. In case you complete them on time, these bonus points over your $G_{E1}, G_{E2}$ and $G_{EF}$ represent +5.5 over your final grade $F$. Students who complete the three UN CC:Learn and the 90,000 XP DataCamp assignments will get +19.6 over their final grade $F$. -->

<!-- As with DataCamp, you are expected to choose the UN CC:Learn course based on your own interests and preferences. Visit the course section to browse the full catalog. -->

**Stickers.** There are some opportunities throughout the semester to get bonus points. In this course, bonus points are allocated in the form of stickers, every sticker stands for 5 bonus points on your $G_{E1}, G_{E2}$ and $G_{EF}$ exams group marks. They are called *stickers* because I give real stickers to my students. Stickers are assigned by merit. It is not very easy to get a sticker, but it is worth a try. The record so far is one student who got 30 bonus points over the $G_{EF}$, and he passed the course partially because of that.

**The wheel of fortune.** I spin a virtual wheel of fortune three times during the semester to randomly allocate bonus points to a lucky group of students. Attendance in these sessions is mandatory to claim the bonus points if you are selected by the wheel. In total, you could earn +0, +5, or +10 bonus points for your next $G_{E1}, G_{E2}$ and $G_{EF}$ exams group marks.

**Mentimeter.** We may have a few sessions that include a Mentimeter activity. This activity may be evaluated, and if it is, the top 10 best answers will earn bonus points. Points will be awarded based on your rank in the top 10: the first place earns +10, the second place earns +9, and so on, with the tenth place earning +1 bonus points for your next $G_{E1}, G_{E2}$ and $G_{EF}$ exams group marks.

**Others.** There may be others listed in the course calendar @sec-schedule or announced during the course of the semester. 

## `r fontawesome::fa("shapes")` Non-graded.

A non-graded activity is a task that does not contribute to the final grade of the course.

**DataCamp webinars.** You are free to attend live webinars organized by DataCamp. See the *live events* DataCamp section for the upcoming webinars in this semester. Please note that you have to register to attend. Let me know which ones you are planning to attend. 

**Videos.** You can record and submit one video per period (the semester has three parts). This is an individual non-graded activity, in Spanish. The submission of this activity is by the discussion forum. I recommend you to upload the video as a YouTube link or any other similar platform so you can submit only the web url in the discussion forum. I would like to avoid others downloading the video, so I believe sharing the link is the best way to submit it. By sharing the video url will allow you to delete your video after the semester ends if you wish. The design of the video and the length is free although you have to start by introducing yourself and the course name. 

There are four types of videos.

* **Type 1: Feynman.** The Feynman technique for teaching and communication is a mental model (a breakdown of a personal thought process) to convey information using concise thoughts and simple language. The Feynman model is named after the Nobel prize-winning physicist Richard Feynman, who was recognized as someone who could clearly explain complex topics in a way that everybody --- even those without degrees in the sciences --- could understand. He was also named *The Smartest Man in the World* in 1979. According to him: *The person who says he knows what he thinks but cannot express it usually does not know what he thinks.* There are four simple steps to the Feynman technique: (1) choose a concept; (2) teach it to a toddler; (3) identify gaps and go back to the source material; (4) review and simplify. Teaching it to a toddler should not take it literally, it basically means that your explanation should be as clear and simple as a toddler could understand it. 

Further details about the Feynman technique here:

```{=html}
<div class="video-embed">
  <iframe src="https://www.youtube-nocookie.com/embed/_f-qkGJBPts" title="YouTube video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
```

* **Type 2: The interview.** You can interview `r fontawesome::fa("video")` someone who can share some thoughts with us. For example, you can interview your mom or dad to discuss topics about his or her job. You are free to design the questions and the format. This could be a good opportunity to know how people in a specific industry tackle business problems, or challenges of people working in the public sector.

* **Type 3: Your pet.** You can show us your pet. Tell us something about your pet, and how special it is for you and your family. Do you have a spider `r fontawesome::fa("spider")`, fish `r fontawesome::fa("fish")`, frog `r fontawesome::fa("frog")`, cat `r fontawesome::fa("cat")`, dog `r fontawesome::fa("dog")`, craw `r fontawesome::fa("crow")`, dragon `r fontawesome::fa("dragon")`? All kinds of pets are welcome.

* **Type 4: Your hobby or talent.** You may have a special artistic `r fontawesome::fa("music")` or sport `r fontawesome::fa("volleyball-ball")` talent you would like to share with us or a hobby which could be interesting for all. This could be a good opportunity to get to know you better.

<!-- **Discussion forums.** -->

<!-- Discussion forums are a good opportunity to discuss topics further while keeping track of ideas, procedures, results and conclusions. The use of discussion forums represent an extension of the class session and learning activities. My advice is to read the course material to be prepared for the discussion forum questions. My view is that discussion forums are not a repository of individual answers but an opportunity to conduct a proper discussion. Then, please make sure that every time you post a contribution you read the current state of the discussion so you can add value to it. We also use the discussion forums as an open space to ask me questions about the course contents. Please subscribe to the discussion forum so you can receive email notifications. This is convenient because I normally do not announce new discussions. There is no fixed frequency for this activity, most of the time it depends on the students interests. You should add your picture in the settings so we can easily match face with name. This is an individual non-graded activity, in Spanish. -->

**Why is $H_3$ a non-graded activity?** The $H_3$ is a special assignment that is designed to help you to practice and study for your final exam by learning from your previous mistakes. It has a deadline but it is a non-graded activity. Given that it is non-graded, this activity is optional. The $H_3$ instructions are the following: You are required to (1) correct all your mistakes in all your previous graded activities, including all the four $E_1$ and $E_2$ questions, and assignments; and (2) complete all your missed extra mark activities, mostly from DataCamp and [UN CC:Learn](https://www.uncclearn.org/). The format and delivery is the same as the rest of the assignments. You can do it in group or individually. You will not receive $H_3$ feedback as by then you will have access to all exam and assignment answers. In any case, you can ask me to review it if necessary. 

<!-- ## `r fontawesome::fa("users")` Co-evaluation. -->
